// Pre-filled options for profile fields

export const DEGREES = [
  "High School",
  "Diploma",
  "Associate's Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "MBA",
  "PhD",
  "Certificate",
  "Professional Degree",
  "Doctorate",
];

export const FIELDS_OF_STUDY = [
  "Computer Science",
  "Business Administration",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Finance",
  "Marketing",
  "Economics",
  "Data Science",
  "Information Technology",
  "Civil Engineering",
  "Medicine",
  "Law",
  "Psychology",
  "Accounting",
  "Human Resources",
  "Communications",
  "Architecture",
  "Graphic Design",
  "Biotechnology",
  "Pharmacy",
  "Commerce",
  "B.Com (Bachelor of Commerce)",
  "M.Com (Master of Commerce)",
  "CA (Chartered Accountancy)",
  "BBA (Bachelor of Business Administration)",
  "Arts",
  "Science",
  "Liberal Arts",
  "English Literature",
  "History",
  "Political Science",
  "Sociology",
  "Philosophy",
];

export const SKILLS = [
  "JavaScript",
  "Python",
  "Project Management",
  "Data Analysis",
  "Microsoft Excel",
  "Communication",
  "Leadership",
  "Marketing",
  "Sales",
  "SQL",
  "React",
  "Financial Analysis",
  "Problem Solving",
  "Customer Service",
  "Team Management",
  "Accounting",
  "Digital Marketing",
  "Graphic Design",
  "Content Writing",
  "Java",
];

export const CERTIFICATIONS = [
  "PMP",
  "AWS Solutions Architect",
  "Google Analytics",
  "Scrum Master",
  "Six Sigma Green Belt",
  "CPA",
  "Microsoft Azure",
  "CISSP",
  "CompTIA A+",
  "Google Cloud Professional",
  "Salesforce Administrator",
  "CFA",
  "SHRM-CP",
  "Digital Marketing",
  "Agile Certified",
  "Other",
];

export const ISSUING_ORGANIZATIONS = [
  "Amazon Web Services",
  "Google",
  "Microsoft",
  "PMI (Project Management Institute)",
  "Scrum Alliance",
  "ISACA",
  "CompTIA",
  "Salesforce",
  "Oracle",
  "Cisco",
  "Adobe",
  "HubSpot",
  "LinkedIn Learning",
  "Coursera",
  "SAP",
  "Other",
];

export const JOB_TITLES = [
  "Software Engineer",
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Data Analyst",
  "Marketing Manager",
  "Sales Manager",
  "HR Manager",
  "Financial Analyst",
  "Operations Manager",
  "Account Executive",
  "Software Developer",
  "UX Designer",
  "Data Scientist",
  "Full Stack Developer",
  "DevOps Engineer",
  "Content Manager",
  "Customer Success Manager",
  "Consultant",
  "CEO/Founder",
  "Director",
];

export const INDIAN_CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Indore",
  "Noida",
  "Gurgaon",
  "Kochi",
  "Coimbatore",
  "Surat",
  "Nagpur",
  "Bhopal",
  "Visakhapatnam",
];
