project_id = "jqynxytwngtytvuzucuo"

[functions.admin-reset-user-password]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = true

[functions.send-company-invitation]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-password-otp]
verify_jwt = false

[functions.verify-password-otp]
verify_jwt = false

[functions.create-member-invitation]
verify_jwt = true

[functions.verify-member-invitation]
verify_jwt = false

[functions.complete-member-invitation]
verify_jwt = false

[functions.resend-member-invitation]
verify_jwt = true

[functions.revoke-member-invitation]
verify_jwt = true

[functions.accept-company-invitation]
verify_jwt = false

[functions.fetch-link-preview]
verify_jwt = false

[functions.get-landing-page]
verify_jwt = false

[functions.process-event-registration]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.export-table-csv]
verify_jwt = false
